import type { Metadata } from "next";

import { siteConfig } from "@/site";

import { ogImageSize } from "./og-image";
import type { PublicRoute } from "./routes";

/** The default document title, also the OG title for the landing page. */
export const siteTitle = `${siteConfig.name} — ${siteConfig.copy.titleSuffix}`;

/**
 * Points at the route generated by app/opengraph-image.tsx.
 *
 * This has to be restated rather than left to the file convention. Next only
 * merges a file-convention OG image into the segment that contains the file
 * (here, the app/ root) — and it skips that merge entirely when the segment's
 * own `openGraph` already declares `images`. Because a page defining
 * `openGraph` *replaces* the root's object wholesale, omitting this drops
 * og:image from every page built by this helper.
 */
const ogImages = [
  {
    url: "/opengraph-image",
    width: ogImageSize.width,
    height: ogImageSize.height,
    alt: siteConfig.copy.ogAlt,
  },
];

/**
 * Published company pages are the one indexable route family that cannot live
 * in `publicRoutes` — the set is data, not code, and changes whenever a report
 * is published. The template literal keeps the escape hatch narrow: every other
 * path must still be a registered route.
 */
type CompanyPagePath = `/interview-questions/${string}`;

/**
 * Role pages, for the same reason: the set is data in `lib/careers/roles.ts`
 * and changes whenever a role opens or closes, so it cannot live in
 * `publicRoutes`. `/careers` itself is a registered route.
 */
type CareersPagePath = `/careers/${string}`;

type BuildMetadataOptions = {
  /** Must be a registered public route, so canonicals and the sitemap agree. */
  path: PublicRoute | CompanyPagePath | CareersPagePath;
  /** Fed through the root `%s · Interview Resources` title template. */
  title: string;
  description: string;
  /** Bypasses the title template. Only the landing page should need this. */
  absoluteTitle?: string;
};

/**
 * Builds page metadata with a self-referential canonical.
 *
 * Next merges metadata *shallowly* — a page that defines `openGraph` replaces
 * the root layout's entire `openGraph` object rather than merging into it. So
 * `type`, `siteName` and `locale` are restated here; dropping them would
 * silently strip those tags from every page that uses this helper. Same reason
 * `twitter` restates `card` and `creator`.
 *
 * Paths stay relative — Next resolves them against `metadataBase`.
 */
export function buildMetadata({
  path,
  title,
  description,
  absoluteTitle,
}: BuildMetadataOptions): Metadata {
  const fullTitle = absoluteTitle ?? `${title} · ${siteConfig.name}`;

  return {
    title: absoluteTitle ? { absolute: absoluteTitle } : title,
    description,
    alternates: {
      canonical: path,
    },
    openGraph: {
      type: "website",
      url: path,
      siteName: siteConfig.name,
      title: fullTitle,
      description,
      locale: "en_US",
      images: ogImages,
    },
    twitter: {
      card: "summary_large_image",
      title: fullTitle,
      description,
      creator: siteConfig.copy.twitterCreator,
      images: ogImages,
    },
  };
}

/**
 * For routes that are reachable but must never be indexed: auth-gated app
 * pages, admin, sign-in, and token-addressed shared reports.
 *
 * Deliberately paired with *not* disallowing these paths in robots.ts — a
 * crawler blocked from fetching the page never sees this directive, and the
 * URL can still surface bare in results.
 */
export const noIndexMetadata: Metadata = {
  robots: {
    index: false,
    follow: false,
  },
};
